In [50]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [51]:
dataset= pd.read_csv('./panic_disorder_dataset_testing.csv')
x=dataset.iloc[:,1:-1]
y=dataset.iloc[:,-1]


In [52]:
x.head()

Age  Gender Family History Personal History Current Stressors  \
0   41    Male            Yes               No              High   
1   20  Female            Yes               No               Low   
2   32    Male            Yes              Yes              High   
3   41  Female            Yes              Yes          Moderate   
4   36  Female            Yes               No              High   

              Symptoms  Severity Impact on Life Demographics Medical History  \
0  Shortness of breath      Mild           Mild        Urban        Diabetes   
1  Shortness of breath      Mild    Significant        Urban          Asthma   
2        Panic attacks    Severe           Mild        Rural   Heart disease   
3  Shortness of breath  Moderate    Significant        Urban   Heart disease   
4           Chest pain    Severe    Significant        Rural          Asthma   

   Psychiatric History Substance Use Coping Mechanisms Social Support  \
0     Bipolar disorder       Alcohol   Seeking therapy            Low   
1     Anxiety disorder         Drugs          Exercise           High   
2     Bipolar disorder         Drugs        Meditation       Moderate   
3     Anxiety disorder          None          Exercise           High   
4  Depressive disorder          None   Seeking therapy            Low   

  Lifestyle Factors  
0          Exercise  
1              Diet  
2          Exercise  
3     Sleep quality  
4          Exercise

In [53]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   Age                  20000 non-null  int64 
 1   Gender               20000 non-null  object
 2   Family History       20000 non-null  object
 3   Personal History     20000 non-null  object
 4   Current Stressors    20000 non-null  object
 5   Symptoms             20000 non-null  object
 6   Severity             20000 non-null  object
 7   Impact on Life       20000 non-null  object
 8   Demographics         20000 non-null  object
 9   Medical History      20000 non-null  object
 10  Psychiatric History  20000 non-null  object
 11  Substance Use        20000 non-null  object
 12  Coping Mechanisms    20000 non-null  object
 13  Social Support       20000 non-null  object
 14  Lifestyle Factors    20000 non-null  object
dtypes: int64(1), object(14)
memory usage: 2.3+ MB


In [54]:
columns = ['Gender','Family History','Personal History','Current Stressors','Symptoms','Severity','Impact on Life','Demographics','Medical History','Psychiatric History','Substance Use','Coping Mechanisms','Social Support','Lifestyle Factors']
mapping={}
for c in columns:
    uniqueval=x[c].unique()
    for i,value in enumerate(uniqueval):
        mapping[value]=i
      
x=x.replace(mapping)  

In [55]:
x.head()

Age  Gender  Family History  Personal History  Current Stressors  Symptoms  \
0   41       0               1                 0                  1         0   
1   20       1               1                 0                  0         0   
2   32       0               1                 1                  1         1   
3   41       1               1                 1                  2         0   
4   36       1               1                 0                  1         2   

   Severity  Impact on Life  Demographics  Medical History  \
0         0               0             0                0   
1         0               1             0                1   
2         1               0             1                2   
3         2               1             0                2   
4         1               1             1                1   

   Psychiatric History  Substance Use  Coping Mechanisms  Social Support  \
0                    0              0                  0               0   
1                    1              1                  0               1   
2                    0              1                  2               2   
3                    1              2                  0               1   
4                    2              2                  0               0   

   Lifestyle Factors  
0                  0  
1                  1  
2                  0  
3                  2  
4                  0

In [56]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [57]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=100,random_state=0)
rfc.fit(x_train,y_train)

RandomForestClassifier(random_state=0)

In [58]:
result=rfc.predict(x_test)

In [59]:
result

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [60]:
y_test=np.array(y_test)
y_test

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [61]:
print(np.concatenate((y_test.reshape(len(y_test),1),result.reshape(len(result),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [62]:
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_test,result)
accuracy_score(y_test,result)

0.973